disabled_rules:
- trailing_whitespace
- trailing_comma

opt_in_rules:
- empty_count
- empty_string
- function_parameter_count
- explicit_type_interface
- force_cast

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- "*/GeneratedMocks.swift"
- "BuildTools"
- "TabNewsUITests/LocalServer/Responses"
- "SourcePackages/"

line_length:
    warning: 181
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
function_parameter_count:
  warning: 3
  error: 4
  
force_cast:
    severity: error
  
explicit_type_interface:
  severity: warning
  
reporter: "xcode"
