ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

default_platform(:ios)

platform :ios do
  desc "Build and Run automated Tests"    
    run_tests(
      scheme: "TabNews (Debug)",
      devices: ["iPhone 15"],
      reset_simulator: true,
      parallel_testing: true,
      ensure_devices_found: true,
      disable_package_automatic_updates: true,
      cloned_source_packages_path: "SourcePackages",
      skip_package_dependencies_resolution:  ENV["HAS_PACKAGES_CACHE_HIT"],
      xcargs: "-skipPackagePluginValidation",
    )
  end
end
