name: "Pull Request"

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build and Run Tests
        runs-on: macos-13

        steps:
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: '15.0.1'
            - uses: actions/checkout@v3
            - name: "Run Formatter"
              run: swiftformat .
            - name: "Run Linter"
              run: swiftlint lint --strict
            - name: Run tests
              run: make test-unit

    
