name: "Pull Request"

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build and Run Tests
        runs-on: macos-13

        steps:
            - uses: actions/checkout@v3
            - name: Set Xcode Version
              run: sudo xcode-select -s '/Applications/Xcode_13.1.app/Contents/Developer'
            - name: Run tests
              run: make test
    
