name: "Pull Request"

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build and Run Tests using iPhone 15
        runs-on: macos-latest

        steps:
           - uses: actions/checkout@v3
           - name: Run tests
             run: make test


    